/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImplementorRouteImport } from './routes/implementor'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImplementorIndexRouteImport } from './routes/implementor.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ImplementorSeAlertsRouteImport } from './routes/implementor.se-alerts'
import { Route as ImplementorReportsRouteImport } from './routes/implementor.reports'
import { Route as ImplementorProgramsRouteImport } from './routes/implementor.programs'
import { Route as ImplementorPatientsRouteImport } from './routes/implementor.patients'
import { Route as ImplementorMessagesRouteImport } from './routes/implementor.messages'
import { Route as ImplementorDashboardRouteImport } from './routes/implementor.dashboard'
import { Route as ImplementorCoverageRouteImport } from './routes/implementor.coverage'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSeAlertsRouteImport } from './routes/admin.se-alerts'
import { Route as AdminProgramsRouteImport } from './routes/admin.programs'
import { Route as AdminOverviewRouteImport } from './routes/admin.overview'
import { Route as AdminInsightsRouteImport } from './routes/admin.insights'
import { Route as AdminImplementorsRouteImport } from './routes/admin.implementors'
import { Route as AdminFacilitiesRouteImport } from './routes/admin.facilities'
import { Route as AdminCoverageRouteImport } from './routes/admin.coverage'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as ImplementorFacilitiesIndexRouteImport } from './routes/implementor.facilities.index'
import { Route as ImplementorFacilitiesSlugRouteImport } from './routes/implementor.facilities.$slug'

const ImplementorRoute = ImplementorRouteImport.update({
  id: '/implementor',
  path: '/implementor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplementorIndexRoute = ImplementorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImplementorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ImplementorSeAlertsRoute = ImplementorSeAlertsRouteImport.update({
  id: '/se-alerts',
  path: '/se-alerts',
  getParentRoute: () => ImplementorRoute,
} as any)
const ImplementorReportsRoute = ImplementorReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ImplementorRoute,
} as any)
const ImplementorProgramsRoute = ImplementorProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => ImplementorRoute,
} as any)
const ImplementorPatientsRoute = ImplementorPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => ImplementorRoute,
} as any)
const ImplementorMessagesRoute = ImplementorMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ImplementorRoute,
} as any)
const ImplementorDashboardRoute = ImplementorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ImplementorRoute,
} as any)
const ImplementorCoverageRoute = ImplementorCoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => ImplementorRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeAlertsRoute = AdminSeAlertsRouteImport.update({
  id: '/se-alerts',
  path: '/se-alerts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInsightsRoute = AdminInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImplementorsRoute = AdminImplementorsRouteImport.update({
  id: '/implementors',
  path: '/implementors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacilitiesRoute = AdminFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoverageRoute = AdminCoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const ImplementorFacilitiesIndexRoute =
  ImplementorFacilitiesIndexRouteImport.update({
    id: '/facilities/',
    path: '/facilities/',
    getParentRoute: () => ImplementorRoute,
  } as any)
const ImplementorFacilitiesSlugRoute =
  ImplementorFacilitiesSlugRouteImport.update({
    id: '/facilities/$slug',
    path: '/facilities/$slug',
    getParentRoute: () => ImplementorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/implementor': typeof ImplementorRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/coverage': typeof AdminCoverageRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/implementors': typeof AdminImplementorsRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/se-alerts': typeof AdminSeAlertsRoute
  '/admin/users': typeof AdminUsersRoute
  '/implementor/coverage': typeof ImplementorCoverageRoute
  '/implementor/dashboard': typeof ImplementorDashboardRoute
  '/implementor/messages': typeof ImplementorMessagesRoute
  '/implementor/patients': typeof ImplementorPatientsRoute
  '/implementor/programs': typeof ImplementorProgramsRoute
  '/implementor/reports': typeof ImplementorReportsRoute
  '/implementor/se-alerts': typeof ImplementorSeAlertsRoute
  '/admin/': typeof AdminIndexRoute
  '/implementor/': typeof ImplementorIndexRoute
  '/implementor/facilities/$slug': typeof ImplementorFacilitiesSlugRoute
  '/implementor/facilities/': typeof ImplementorFacilitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/coverage': typeof AdminCoverageRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/implementors': typeof AdminImplementorsRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/se-alerts': typeof AdminSeAlertsRoute
  '/admin/users': typeof AdminUsersRoute
  '/implementor/coverage': typeof ImplementorCoverageRoute
  '/implementor/dashboard': typeof ImplementorDashboardRoute
  '/implementor/messages': typeof ImplementorMessagesRoute
  '/implementor/patients': typeof ImplementorPatientsRoute
  '/implementor/programs': typeof ImplementorProgramsRoute
  '/implementor/reports': typeof ImplementorReportsRoute
  '/implementor/se-alerts': typeof ImplementorSeAlertsRoute
  '/admin': typeof AdminIndexRoute
  '/implementor': typeof ImplementorIndexRoute
  '/implementor/facilities/$slug': typeof ImplementorFacilitiesSlugRoute
  '/implementor/facilities': typeof ImplementorFacilitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/implementor': typeof ImplementorRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/coverage': typeof AdminCoverageRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/implementors': typeof AdminImplementorsRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/se-alerts': typeof AdminSeAlertsRoute
  '/admin/users': typeof AdminUsersRoute
  '/implementor/coverage': typeof ImplementorCoverageRoute
  '/implementor/dashboard': typeof ImplementorDashboardRoute
  '/implementor/messages': typeof ImplementorMessagesRoute
  '/implementor/patients': typeof ImplementorPatientsRoute
  '/implementor/programs': typeof ImplementorProgramsRoute
  '/implementor/reports': typeof ImplementorReportsRoute
  '/implementor/se-alerts': typeof ImplementorSeAlertsRoute
  '/admin/': typeof AdminIndexRoute
  '/implementor/': typeof ImplementorIndexRoute
  '/implementor/facilities/$slug': typeof ImplementorFacilitiesSlugRoute
  '/implementor/facilities/': typeof ImplementorFacilitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/implementor'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/coverage'
    | '/admin/facilities'
    | '/admin/implementors'
    | '/admin/insights'
    | '/admin/overview'
    | '/admin/programs'
    | '/admin/se-alerts'
    | '/admin/users'
    | '/implementor/coverage'
    | '/implementor/dashboard'
    | '/implementor/messages'
    | '/implementor/patients'
    | '/implementor/programs'
    | '/implementor/reports'
    | '/implementor/se-alerts'
    | '/admin/'
    | '/implementor/'
    | '/implementor/facilities/$slug'
    | '/implementor/facilities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/coverage'
    | '/admin/facilities'
    | '/admin/implementors'
    | '/admin/insights'
    | '/admin/overview'
    | '/admin/programs'
    | '/admin/se-alerts'
    | '/admin/users'
    | '/implementor/coverage'
    | '/implementor/dashboard'
    | '/implementor/messages'
    | '/implementor/patients'
    | '/implementor/programs'
    | '/implementor/reports'
    | '/implementor/se-alerts'
    | '/admin'
    | '/implementor'
    | '/implementor/facilities/$slug'
    | '/implementor/facilities'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/implementor'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/coverage'
    | '/admin/facilities'
    | '/admin/implementors'
    | '/admin/insights'
    | '/admin/overview'
    | '/admin/programs'
    | '/admin/se-alerts'
    | '/admin/users'
    | '/implementor/coverage'
    | '/implementor/dashboard'
    | '/implementor/messages'
    | '/implementor/patients'
    | '/implementor/programs'
    | '/implementor/reports'
    | '/implementor/se-alerts'
    | '/admin/'
    | '/implementor/'
    | '/implementor/facilities/$slug'
    | '/implementor/facilities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ImplementorRoute: typeof ImplementorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/implementor': {
      id: '/implementor'
      path: '/implementor'
      fullPath: '/implementor'
      preLoaderRoute: typeof ImplementorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implementor/': {
      id: '/implementor/'
      path: '/'
      fullPath: '/implementor/'
      preLoaderRoute: typeof ImplementorIndexRouteImport
      parentRoute: typeof ImplementorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/implementor/se-alerts': {
      id: '/implementor/se-alerts'
      path: '/se-alerts'
      fullPath: '/implementor/se-alerts'
      preLoaderRoute: typeof ImplementorSeAlertsRouteImport
      parentRoute: typeof ImplementorRoute
    }
    '/implementor/reports': {
      id: '/implementor/reports'
      path: '/reports'
      fullPath: '/implementor/reports'
      preLoaderRoute: typeof ImplementorReportsRouteImport
      parentRoute: typeof ImplementorRoute
    }
    '/implementor/programs': {
      id: '/implementor/programs'
      path: '/programs'
      fullPath: '/implementor/programs'
      preLoaderRoute: typeof ImplementorProgramsRouteImport
      parentRoute: typeof ImplementorRoute
    }
    '/implementor/patients': {
      id: '/implementor/patients'
      path: '/patients'
      fullPath: '/implementor/patients'
      preLoaderRoute: typeof ImplementorPatientsRouteImport
      parentRoute: typeof ImplementorRoute
    }
    '/implementor/messages': {
      id: '/implementor/messages'
      path: '/messages'
      fullPath: '/implementor/messages'
      preLoaderRoute: typeof ImplementorMessagesRouteImport
      parentRoute: typeof ImplementorRoute
    }
    '/implementor/dashboard': {
      id: '/implementor/dashboard'
      path: '/dashboard'
      fullPath: '/implementor/dashboard'
      preLoaderRoute: typeof ImplementorDashboardRouteImport
      parentRoute: typeof ImplementorRoute
    }
    '/implementor/coverage': {
      id: '/implementor/coverage'
      path: '/coverage'
      fullPath: '/implementor/coverage'
      preLoaderRoute: typeof ImplementorCoverageRouteImport
      parentRoute: typeof ImplementorRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/se-alerts': {
      id: '/admin/se-alerts'
      path: '/se-alerts'
      fullPath: '/admin/se-alerts'
      preLoaderRoute: typeof AdminSeAlertsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/insights': {
      id: '/admin/insights'
      path: '/insights'
      fullPath: '/admin/insights'
      preLoaderRoute: typeof AdminInsightsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/implementors': {
      id: '/admin/implementors'
      path: '/implementors'
      fullPath: '/admin/implementors'
      preLoaderRoute: typeof AdminImplementorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facilities': {
      id: '/admin/facilities'
      path: '/facilities'
      fullPath: '/admin/facilities'
      preLoaderRoute: typeof AdminFacilitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coverage': {
      id: '/admin/coverage'
      path: '/coverage'
      fullPath: '/admin/coverage'
      preLoaderRoute: typeof AdminCoverageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/implementor/facilities/': {
      id: '/implementor/facilities/'
      path: '/facilities'
      fullPath: '/implementor/facilities/'
      preLoaderRoute: typeof ImplementorFacilitiesIndexRouteImport
      parentRoute: typeof ImplementorRoute
    }
    '/implementor/facilities/$slug': {
      id: '/implementor/facilities/$slug'
      path: '/facilities/$slug'
      fullPath: '/implementor/facilities/$slug'
      preLoaderRoute: typeof ImplementorFacilitiesSlugRouteImport
      parentRoute: typeof ImplementorRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminCoverageRoute: typeof AdminCoverageRoute
  AdminFacilitiesRoute: typeof AdminFacilitiesRoute
  AdminImplementorsRoute: typeof AdminImplementorsRoute
  AdminInsightsRoute: typeof AdminInsightsRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminProgramsRoute: typeof AdminProgramsRoute
  AdminSeAlertsRoute: typeof AdminSeAlertsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminCoverageRoute: AdminCoverageRoute,
  AdminFacilitiesRoute: AdminFacilitiesRoute,
  AdminImplementorsRoute: AdminImplementorsRoute,
  AdminInsightsRoute: AdminInsightsRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminProgramsRoute: AdminProgramsRoute,
  AdminSeAlertsRoute: AdminSeAlertsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ImplementorRouteChildren {
  ImplementorCoverageRoute: typeof ImplementorCoverageRoute
  ImplementorDashboardRoute: typeof ImplementorDashboardRoute
  ImplementorMessagesRoute: typeof ImplementorMessagesRoute
  ImplementorPatientsRoute: typeof ImplementorPatientsRoute
  ImplementorProgramsRoute: typeof ImplementorProgramsRoute
  ImplementorReportsRoute: typeof ImplementorReportsRoute
  ImplementorSeAlertsRoute: typeof ImplementorSeAlertsRoute
  ImplementorIndexRoute: typeof ImplementorIndexRoute
  ImplementorFacilitiesSlugRoute: typeof ImplementorFacilitiesSlugRoute
  ImplementorFacilitiesIndexRoute: typeof ImplementorFacilitiesIndexRoute
}

const ImplementorRouteChildren: ImplementorRouteChildren = {
  ImplementorCoverageRoute: ImplementorCoverageRoute,
  ImplementorDashboardRoute: ImplementorDashboardRoute,
  ImplementorMessagesRoute: ImplementorMessagesRoute,
  ImplementorPatientsRoute: ImplementorPatientsRoute,
  ImplementorProgramsRoute: ImplementorProgramsRoute,
  ImplementorReportsRoute: ImplementorReportsRoute,
  ImplementorSeAlertsRoute: ImplementorSeAlertsRoute,
  ImplementorIndexRoute: ImplementorIndexRoute,
  ImplementorFacilitiesSlugRoute: ImplementorFacilitiesSlugRoute,
  ImplementorFacilitiesIndexRoute: ImplementorFacilitiesIndexRoute,
}

const ImplementorRouteWithChildren = ImplementorRoute._addFileChildren(
  ImplementorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ImplementorRoute: ImplementorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
