/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImplementorRouteImport } from './routes/implementor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImplementorIndexRouteImport } from './routes/implementor.index'
import { Route as ImplementorSeAlertsRouteImport } from './routes/implementor.se-alerts'
import { Route as ImplementorReportsRouteImport } from './routes/implementor.reports'
import { Route as ImplementorProgramsRouteImport } from './routes/implementor.programs'
import { Route as ImplementorPatientsRouteImport } from './routes/implementor.patients'
import { Route as ImplementorDashboardRouteImport } from './routes/implementor.dashboard'
import { Route as ImplementorCoverageRouteImport } from './routes/implementor.coverage'
import { Route as ImplementorFacilitiesIndexRouteImport } from './routes/implementor.facilities.index'
import { Route as ImplementorFacilitiesSlugRouteImport } from './routes/implementor.facilities.$slug'

const ImplementorRoute = ImplementorRouteImport.update({
  id: '/implementor',
  path: '/implementor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplementorIndexRoute = ImplementorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImplementorRoute,
} as any)
const ImplementorSeAlertsRoute = ImplementorSeAlertsRouteImport.update({
  id: '/se-alerts',
  path: '/se-alerts',
  getParentRoute: () => ImplementorRoute,
} as any)
const ImplementorReportsRoute = ImplementorReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ImplementorRoute,
} as any)
const ImplementorProgramsRoute = ImplementorProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => ImplementorRoute,
} as any)
const ImplementorPatientsRoute = ImplementorPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => ImplementorRoute,
} as any)
const ImplementorDashboardRoute = ImplementorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ImplementorRoute,
} as any)
const ImplementorCoverageRoute = ImplementorCoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => ImplementorRoute,
} as any)
const ImplementorFacilitiesIndexRoute =
  ImplementorFacilitiesIndexRouteImport.update({
    id: '/facilities/',
    path: '/facilities/',
    getParentRoute: () => ImplementorRoute,
  } as any)
const ImplementorFacilitiesSlugRoute =
  ImplementorFacilitiesSlugRouteImport.update({
    id: '/facilities/$slug',
    path: '/facilities/$slug',
    getParentRoute: () => ImplementorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/implementor': typeof ImplementorRouteWithChildren
  '/implementor/coverage': typeof ImplementorCoverageRoute
  '/implementor/dashboard': typeof ImplementorDashboardRoute
  '/implementor/patients': typeof ImplementorPatientsRoute
  '/implementor/programs': typeof ImplementorProgramsRoute
  '/implementor/reports': typeof ImplementorReportsRoute
  '/implementor/se-alerts': typeof ImplementorSeAlertsRoute
  '/implementor/': typeof ImplementorIndexRoute
  '/implementor/facilities/$slug': typeof ImplementorFacilitiesSlugRoute
  '/implementor/facilities/': typeof ImplementorFacilitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/implementor/coverage': typeof ImplementorCoverageRoute
  '/implementor/dashboard': typeof ImplementorDashboardRoute
  '/implementor/patients': typeof ImplementorPatientsRoute
  '/implementor/programs': typeof ImplementorProgramsRoute
  '/implementor/reports': typeof ImplementorReportsRoute
  '/implementor/se-alerts': typeof ImplementorSeAlertsRoute
  '/implementor': typeof ImplementorIndexRoute
  '/implementor/facilities/$slug': typeof ImplementorFacilitiesSlugRoute
  '/implementor/facilities': typeof ImplementorFacilitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/implementor': typeof ImplementorRouteWithChildren
  '/implementor/coverage': typeof ImplementorCoverageRoute
  '/implementor/dashboard': typeof ImplementorDashboardRoute
  '/implementor/patients': typeof ImplementorPatientsRoute
  '/implementor/programs': typeof ImplementorProgramsRoute
  '/implementor/reports': typeof ImplementorReportsRoute
  '/implementor/se-alerts': typeof ImplementorSeAlertsRoute
  '/implementor/': typeof ImplementorIndexRoute
  '/implementor/facilities/$slug': typeof ImplementorFacilitiesSlugRoute
  '/implementor/facilities/': typeof ImplementorFacilitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/implementor'
    | '/implementor/coverage'
    | '/implementor/dashboard'
    | '/implementor/patients'
    | '/implementor/programs'
    | '/implementor/reports'
    | '/implementor/se-alerts'
    | '/implementor/'
    | '/implementor/facilities/$slug'
    | '/implementor/facilities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/implementor/coverage'
    | '/implementor/dashboard'
    | '/implementor/patients'
    | '/implementor/programs'
    | '/implementor/reports'
    | '/implementor/se-alerts'
    | '/implementor'
    | '/implementor/facilities/$slug'
    | '/implementor/facilities'
  id:
    | '__root__'
    | '/'
    | '/implementor'
    | '/implementor/coverage'
    | '/implementor/dashboard'
    | '/implementor/patients'
    | '/implementor/programs'
    | '/implementor/reports'
    | '/implementor/se-alerts'
    | '/implementor/'
    | '/implementor/facilities/$slug'
    | '/implementor/facilities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImplementorRoute: typeof ImplementorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/implementor': {
      id: '/implementor'
      path: '/implementor'
      fullPath: '/implementor'
      preLoaderRoute: typeof ImplementorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implementor/': {
      id: '/implementor/'
      path: '/'
      fullPath: '/implementor/'
      preLoaderRoute: typeof ImplementorIndexRouteImport
      parentRoute: typeof ImplementorRoute
    }
    '/implementor/se-alerts': {
      id: '/implementor/se-alerts'
      path: '/se-alerts'
      fullPath: '/implementor/se-alerts'
      preLoaderRoute: typeof ImplementorSeAlertsRouteImport
      parentRoute: typeof ImplementorRoute
    }
    '/implementor/reports': {
      id: '/implementor/reports'
      path: '/reports'
      fullPath: '/implementor/reports'
      preLoaderRoute: typeof ImplementorReportsRouteImport
      parentRoute: typeof ImplementorRoute
    }
    '/implementor/programs': {
      id: '/implementor/programs'
      path: '/programs'
      fullPath: '/implementor/programs'
      preLoaderRoute: typeof ImplementorProgramsRouteImport
      parentRoute: typeof ImplementorRoute
    }
    '/implementor/patients': {
      id: '/implementor/patients'
      path: '/patients'
      fullPath: '/implementor/patients'
      preLoaderRoute: typeof ImplementorPatientsRouteImport
      parentRoute: typeof ImplementorRoute
    }
    '/implementor/dashboard': {
      id: '/implementor/dashboard'
      path: '/dashboard'
      fullPath: '/implementor/dashboard'
      preLoaderRoute: typeof ImplementorDashboardRouteImport
      parentRoute: typeof ImplementorRoute
    }
    '/implementor/coverage': {
      id: '/implementor/coverage'
      path: '/coverage'
      fullPath: '/implementor/coverage'
      preLoaderRoute: typeof ImplementorCoverageRouteImport
      parentRoute: typeof ImplementorRoute
    }
    '/implementor/facilities/': {
      id: '/implementor/facilities/'
      path: '/facilities'
      fullPath: '/implementor/facilities/'
      preLoaderRoute: typeof ImplementorFacilitiesIndexRouteImport
      parentRoute: typeof ImplementorRoute
    }
    '/implementor/facilities/$slug': {
      id: '/implementor/facilities/$slug'
      path: '/facilities/$slug'
      fullPath: '/implementor/facilities/$slug'
      preLoaderRoute: typeof ImplementorFacilitiesSlugRouteImport
      parentRoute: typeof ImplementorRoute
    }
  }
}

interface ImplementorRouteChildren {
  ImplementorCoverageRoute: typeof ImplementorCoverageRoute
  ImplementorDashboardRoute: typeof ImplementorDashboardRoute
  ImplementorPatientsRoute: typeof ImplementorPatientsRoute
  ImplementorProgramsRoute: typeof ImplementorProgramsRoute
  ImplementorReportsRoute: typeof ImplementorReportsRoute
  ImplementorSeAlertsRoute: typeof ImplementorSeAlertsRoute
  ImplementorIndexRoute: typeof ImplementorIndexRoute
  ImplementorFacilitiesSlugRoute: typeof ImplementorFacilitiesSlugRoute
  ImplementorFacilitiesIndexRoute: typeof ImplementorFacilitiesIndexRoute
}

const ImplementorRouteChildren: ImplementorRouteChildren = {
  ImplementorCoverageRoute: ImplementorCoverageRoute,
  ImplementorDashboardRoute: ImplementorDashboardRoute,
  ImplementorPatientsRoute: ImplementorPatientsRoute,
  ImplementorProgramsRoute: ImplementorProgramsRoute,
  ImplementorReportsRoute: ImplementorReportsRoute,
  ImplementorSeAlertsRoute: ImplementorSeAlertsRoute,
  ImplementorIndexRoute: ImplementorIndexRoute,
  ImplementorFacilitiesSlugRoute: ImplementorFacilitiesSlugRoute,
  ImplementorFacilitiesIndexRoute: ImplementorFacilitiesIndexRoute,
}

const ImplementorRouteWithChildren = ImplementorRoute._addFileChildren(
  ImplementorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImplementorRoute: ImplementorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
