/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImplementorRouteImport } from './routes/implementor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImplementorIndexRouteImport } from './routes/implementor.index'
import { Route as ImplementorFacilitiesRouteImport } from './routes/implementor.facilities'
import { Route as ImplementorDashboardRouteImport } from './routes/implementor.dashboard'
import { Route as ImplementorCoverageRouteImport } from './routes/implementor.coverage'

const ImplementorRoute = ImplementorRouteImport.update({
  id: '/implementor',
  path: '/implementor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplementorIndexRoute = ImplementorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImplementorRoute,
} as any)
const ImplementorFacilitiesRoute = ImplementorFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => ImplementorRoute,
} as any)
const ImplementorDashboardRoute = ImplementorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ImplementorRoute,
} as any)
const ImplementorCoverageRoute = ImplementorCoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => ImplementorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/implementor': typeof ImplementorRouteWithChildren
  '/implementor/coverage': typeof ImplementorCoverageRoute
  '/implementor/dashboard': typeof ImplementorDashboardRoute
  '/implementor/facilities': typeof ImplementorFacilitiesRoute
  '/implementor/': typeof ImplementorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/implementor/coverage': typeof ImplementorCoverageRoute
  '/implementor/dashboard': typeof ImplementorDashboardRoute
  '/implementor/facilities': typeof ImplementorFacilitiesRoute
  '/implementor': typeof ImplementorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/implementor': typeof ImplementorRouteWithChildren
  '/implementor/coverage': typeof ImplementorCoverageRoute
  '/implementor/dashboard': typeof ImplementorDashboardRoute
  '/implementor/facilities': typeof ImplementorFacilitiesRoute
  '/implementor/': typeof ImplementorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/implementor'
    | '/implementor/coverage'
    | '/implementor/dashboard'
    | '/implementor/facilities'
    | '/implementor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/implementor/coverage'
    | '/implementor/dashboard'
    | '/implementor/facilities'
    | '/implementor'
  id:
    | '__root__'
    | '/'
    | '/implementor'
    | '/implementor/coverage'
    | '/implementor/dashboard'
    | '/implementor/facilities'
    | '/implementor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImplementorRoute: typeof ImplementorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/implementor': {
      id: '/implementor'
      path: '/implementor'
      fullPath: '/implementor'
      preLoaderRoute: typeof ImplementorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implementor/': {
      id: '/implementor/'
      path: '/'
      fullPath: '/implementor/'
      preLoaderRoute: typeof ImplementorIndexRouteImport
      parentRoute: typeof ImplementorRoute
    }
    '/implementor/facilities': {
      id: '/implementor/facilities'
      path: '/facilities'
      fullPath: '/implementor/facilities'
      preLoaderRoute: typeof ImplementorFacilitiesRouteImport
      parentRoute: typeof ImplementorRoute
    }
    '/implementor/dashboard': {
      id: '/implementor/dashboard'
      path: '/dashboard'
      fullPath: '/implementor/dashboard'
      preLoaderRoute: typeof ImplementorDashboardRouteImport
      parentRoute: typeof ImplementorRoute
    }
    '/implementor/coverage': {
      id: '/implementor/coverage'
      path: '/coverage'
      fullPath: '/implementor/coverage'
      preLoaderRoute: typeof ImplementorCoverageRouteImport
      parentRoute: typeof ImplementorRoute
    }
  }
}

interface ImplementorRouteChildren {
  ImplementorCoverageRoute: typeof ImplementorCoverageRoute
  ImplementorDashboardRoute: typeof ImplementorDashboardRoute
  ImplementorFacilitiesRoute: typeof ImplementorFacilitiesRoute
  ImplementorIndexRoute: typeof ImplementorIndexRoute
}

const ImplementorRouteChildren: ImplementorRouteChildren = {
  ImplementorCoverageRoute: ImplementorCoverageRoute,
  ImplementorDashboardRoute: ImplementorDashboardRoute,
  ImplementorFacilitiesRoute: ImplementorFacilitiesRoute,
  ImplementorIndexRoute: ImplementorIndexRoute,
}

const ImplementorRouteWithChildren = ImplementorRoute._addFileChildren(
  ImplementorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImplementorRoute: ImplementorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
